### ISSUE TITLE
Не могу добавить интеграцию LedFX - Unknown error occurred

### ISSUE THREAD

**Issue by DivanX10** [dmamontov/hass-ledfx#7]
Нельзя авторизироваться без логина и пароля, но можно зайти, указав любой пароль 

![image](https://user-images.githubusercontent.com/64090632/151229692-a30a5af2-4071-47f7-947c-6f409e556721.png)

В аддоне LedFX включено разрешение для авторизации

```
certfile: fullchain.pem
keyfile: privkey.pem
ssl: false
leave_front_door_open: true
```

<details>
  <summary><b>Первый лог</b></summary>
  

```
Logger: aiohttp.server
Source: custom_components/ledfx/config_flow.py:54
Integration: LedFx (documentation, issues)
First occurred: 22:04:55 (1 occurrences)
Last logged: 22:04:55

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/ledfx/config_flow.py", line 54, in async_step_auth
    user_input[CONF_USERNAME]
KeyError: 'username'
```
  
</details>

<details>
  <summary><b>Второй лог</b></summary>
  

```
2022-01-26 22:04:10 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:04:10 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:04:20 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:04:20 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:04:30 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:04:30 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:04:40 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:04:40 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:04:50 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:04:50 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:04:55 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/ledfx/config_flow.py", line 54, in async_step_auth
user_input[CONF_USERNAME]
KeyError: 'username'
2022-01-26 22:05:00 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:05:00 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:05:10 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:05:10 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:05:20 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:05:20 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:05:30 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:05:30 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:05:40 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:05:40 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:05:50 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:05:50 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:06:00 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:06:00 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:06:10 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:06:10 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:06:20 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:06:20 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:06:30 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:06:30 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:06:40 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:06:40 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:06:50 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:06:50 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:07:00 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:07:00 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:07:10 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:07:10 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:07:20 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:07:20 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:07:30 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:07:30 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:07:40 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:07:40 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:07:50 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:07:50 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:08:00 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:08:00 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:08:10 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:08:10 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:08:20 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:08:20 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:08:30 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:08:30 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:08:40 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:08:40 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:08:50 DEBUG (MainThread) [custom_components.ledfx.core.ledfx] ERROR LedFx: Connection error ConnectError('All connection attempts failed')
2022-01-26 22:08:50 DEBUG (MainThread) [custom_components.ledfx.core.worker] LedFx updated (localhost:5333)
2022-01-26 22:08:58 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/ledfx/config_flow.py", line 54, in async_step_auth
user_input[CONF_USERNAME]
KeyError: 'username'
```
  
</details>

**Comment by dmamontov** [comment]
@DivanX10 https://github.com/dmamontov/hass-ledfx/releases/tag/v1.2.1 проверяй)

**Comment by DivanX10** [comment]
Спасибо. Теперь можно заходить без логина и пароля.
